# Generated by Django 4.2.7 on 2023-11-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_useravailability_shift_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravailability',
            name='day',
            field=models.DateField(),
        ),
    ]
