# Generated by Django 4.2.7 on 2023-11-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_alter_useravailability_shift_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravailability',
            name='shift_preferences',
            field=models.CharField(choices=[('First_Shift', '8:00-16:00'), ('Second_Shift', '14:00-22:00')], max_length=20),
        ),
    ]
