# Generated by Django 4.2.7 on 2023-12-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_rename_user_id_useravailability_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='useravailability',
            old_name='user',
            new_name='user_id',
        ),
    ]
