# Generated by Django 4.2.7 on 2023-12-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_rename_user_schedule_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='user_id',
            new_name='user',
        ),
    ]
