# Generated by Django 4.2.5 on 2023-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_name',
            field=models.CharField(choices=[('First_Shift', '8:00-16:00'), ('Second_Shift', '14:00-22:00')], max_length=150),
        ),
        migrations.AlterField(
            model_name='useravailability',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='useravailability',
            name='shift_preferences',
            field=models.CharField(choices=[('First_Shift', '8:00-16:00'), ('Second_Shift', '14:00-22:00')], max_length=150),
        ),
    ]
