# Generated by Django 4.2.7 on 2023-11-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_alter_useravailability_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useravailability',
            old_name='user_id',
            new_name='user',
        ),
    ]
