# Generated by Django 4.2.7 on 2023-11-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_rename_user_id_useravailability_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useravailability',
            old_name='user',
            new_name='user_id',
        ),
    ]
