# Generated by Django 4.2.7 on 2023-12-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0018_sum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sum',
        ),
        migrations.AddField(
            model_name='schedule',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
